CREATE TABLE b_custom_notes (
     ID int AUTO_INCREMENT PRIMARY KEY,
     TITLE varchar(255) NOT NULL,
     CONTENT text,
     CREATED_AT datetime DEFAULT CURRENT_TIMESTAMP,
     UPDATED_AT datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);